# Generated by Django 4.2.4 on 2023-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_cantidad_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
