# Generated by Django 4.2.4 on 2023-11-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(max_length=30),
        ),
    ]
