# Generated by Django 4.2.7 on 2023-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_alter_cantidad_id_alter_compra_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Link',
            field=models.CharField(max_length=255),
        ),
    ]
